### ISSUE TITLE
High I/O Usage and High Thread Count 

### ISSUE THREAD

**Issue by Algo1337** [joysticks/Dread#2]
When the server is under attack on the specified port being used to host the net. The net in-fact overwelms the server due to trying to parse and respond to DDoS Request(s). This application has zero network protection

**Comment by joysticks** [comment]
This source is essentially a QBOT at heart, and was not designed with security in mind. This variant was made to be a learning tool for people new to Linux botnet malware. A simple solution to avoid DDoS attacks on your server is to not share the server IP with people who shouldn't have it!

**Comment by Algo1337** [comment]
World wide scans are a thing buddy, You ever heard of em? Not sharing the backend IP to the server isn't gonnah help it
